#! /bin/sh

if [ -x /usr/bin/gconftool ]; then
  gconftool --recursive-unset /apps/colem
fi

if [ -x /usr/bin/update-mime-database ]; then
  update-mime-database /usr/share/mime
fi

if [ -x /usr/bin/update-desktop-database ]; then
  update-desktop-database /usr/share/applications
fi

if [ -x /usr/bin/hildon-update-category-database ]; then
  hildon-update-category-database /usr/share/mime
fi

if [ -x /usr/bin/gtk-update-icon-cache ]; then
  gtk-update-icon-cache -f /usr/share/icons/hicolor
fi

if [ -x /usr/bin/maemo-select-menu-location ]; then
  maemo-select-menu-location colem.desktop
fi

exit 0
